### ISSUE TITLE
Adição do Link https://impulso.link/communup ao Menu "Solicite uma Mentoria"

### ISSUE THREAD

**Issue by cenicoemir** [universoimpulso/communup#4]
Verifiquei que no menu, a opção Solicite uma Mentoria não aponta para lugar algum, poderiamos apontar para o https://impulso.link/communup ? @IgorHalfeld Não sou familiarizado o suficiente com Vue/Quasar para ajustar isso. xD

**Comment by IgorHalfeld** [comment]
@cenicoemir o Vue é bem intuitivo, o que você achar, realmente é hahaha

No componente `layouts/Default.vue` tem o `Drawer` e no item de solicitar uma mentoria

```html
<q-item clickable @click="request">
  <q-item-section avatar>
    <q-icon name="chat" />
  </q-item-section>
  <q-item-section class="text-uppercase text-grey-9">
    Solicite uma mentoria
  </q-item-section>
</q-item>
```

basta colocar o `@click="request"` com a fn request que é só você escrever ela em methods
_colocar `@click="request()"` ou o `@click="request"` para o Vue tanto faz_

```js
methods: {
  toggleDrawerOpen() {
    this.leftDrawerOpen = !this.leftDrawerOpen;
  },
  goFor(where) {
    this.$router.push({ name: where });
    this.leftDrawerOpen = false;
  },
  requestMetoring() {
    window.open(YOUR_URL_HERE, '_blank')
  }
}
```

**Comment by cenicoemir** [comment]
Saquei, vou meter lá.
